# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    param_fetcher_listener: true
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
        mime-types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=2.0']
    serializer:
        serialize_null: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    versioning:
        enabled: true
        resolvers:
            media_type: #Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
